# fly.toml app configuration file generated for moeyy-alltube on 2023-08-27T02:35:41+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "moeyy-alltube"
primary_region = "sin"

[build]

[http_service]
  internal_port = 80
  force_https = false
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 0
  processes = ["app"]
